### ISSUE TITLE
Can we continue with reading file even if we encounter any issue in any line

### ISSUE THREAD

**Issue by mom1705** [ben-strasser/fast-cpp-csv-parser#102]
because of try/catch outside while,  am not able to do so. I would like all invalid line to log and move forward reading full file. Is it possible ?

**Comment by mom1705** [comment]
i would also like line written with starting "#" to be ignored and treated as comments, is it possible

ex.
# here is my test for comment

**Comment by ben-strasser** [comment]
You can ignore comment lines but resuming on error is not possible.

**Comment by mom1705** [comment]
oh, can't we change something which can enable parsing further after logging
