### ISSUE TITLE
Static_assert failed due to requirement 'sizeof...(ColType) >= 3U' "not enough columns specified"

### ISSUE THREAD

**Issue by jayesh0vasudeva** [ben-strasser/fast-cpp-csv-parser#107]
`int main(){
    
    io::CSVReader<3> in("g.csv");
    in.read_header(io::ignore_extra_column, "index", "g", "label");
    vector<double> g;
    vector<int> labels;
    int label; double score;
    while(in.read_row(score, label)){
        cout<<score<<" : "<<label;
    // do stuff with the data
    }
    
    
    return 0;
}`

**Comment by jayesh0vasudeva** [comment]
I have 3 columns in my dataset: index, g and label. I can't figure out the problem

**Comment by ben-strasser** [comment]
> while(in.read_row(score, label)

not enough coumns specified.

Try

> while(in.read_row(index, score, label)

or something similar. :)
