### ISSUE TITLE
Can ^M at end of line be trimmed

### ISSUE THREAD

**Issue by mom1705** [ben-strasser/fast-cpp-csv-parser#109]
CSVReader<3, trim_chars<' ', '\t', '\r', '\n', '^M'>, no_quote_escape<','>, throw_on_overflow, no_comment> in(strFileName.c_str());

I have give n above directive but with below csv file, 
^M
1256,3647,172.70.108.65^M
1276,3098,172.29.123.233/r
1234, 5678, 172.70.109.25

I was expecting ^M, \r to be trimmed and use other data but it is not working as desired.
Can you pls help me with correct directive

**Comment by ben-strasser** [comment]
What character is ^M ? This is not a legal C single character escape 
sequence.

**Comment by mom1705** [comment]
^M comes when csv file from Windows to linux is copied.
Actually I don't need ^M removal /ignorance but somehow "\r" is being treated as fresh line, is there a possibility to be treated in same line where it is physically placed ?

**Comment by mom1705** [comment]
closing as I got the solution
