### ISSUE TITLE
Ignore values

### ISSUE THREAD

**Issue by michael-customlbs** [ben-strasser/fast-cpp-csv-parser#11]
Sometimes I don't want to read all values.
Is there a way to ignore columns e.g.:
```
int i;
in.read_row(i, io::ignore, io::ignore, io::ignore);
```

This would save me a lot of lines.

**Comment by ben-strasser** [comment]
Hi,

just do

char*ignore;
...
in.read_row(i, ignore, ignore, ignore);

As this involves no copy it should be fast.

If you want to ignore all values of a column then using io::ignore_extra_column
is probably better though.

Best Regards
Ben Strasser
