### ISSUE TITLE
Process a CSV where each line has varying headers

### ISSUE THREAD

**Issue by deathwishdave** [ben-strasser/fast-cpp-csv-parser#112]
Hello, I am trying to process a common format for weather data, the EPW file. Here is an [example ](https://energyplus.net/weather-download/north_and_central_america_wmo_region_4/USA/FL/USA_FL_Crestview-Bob.Sikes.AP.722215_TMY3/USA_FL_Crestview-Bob.Sikes.AP.722215_TMY3.epw)

The first 8 lines contain varying csv data, each line with its own headers.

Can this be processed with this library please?

**Comment by ben-strasser** [comment]
Hi,

What you can do is create a CSVReader, then call 8 times next_line on 
it. This will give you the first eight lines unmodified. Next you call 
set_header to give the column names (which are only used in the error 
messages), and then read_row will work for the rest.

This setup will work, but it is kind of a hack. I am uncertain whether 
you gain enough using this library for this application to justify the 
extra dependency.

Best Regards

Ben Strasser
