### ISSUE TITLE
free(): invalid pointer

### ISSUE THREAD

**Issue by lk-dll** [ben-strasser/fast-cpp-csv-parser#116]
Hi,

trying to go through 2 files a read the content, read in a separate run is ok, but when I run the code like in my example I got an error:

    free(): invalid pointer

My program is like:

    int main( void ){
        // definitions, etc.

        processFile( path_1, ...arrays, variables );
        processFile( path_2, ...arrays, variables );
    }

    void processFile( char *path, ...arrays, variables ){
        // definitions
        io::CSVReader< 44 > in( path );
        in.read_header( io::ignore_extra_column, ...column_names... );
    
        while( in.read_row( ...columns... ) ){
            // do some stuff with lines
        }

        return;
    }

Pls help.

**Comment by ben-strasser** [comment]
Hi,

thanks for the bug report. Can you provide a minimum compiling example 
with CSV file?

Best Regards
Dr. Ben Strasser

**Comment by lk-dll** [comment]
Hi Ben, 
I'm not able to reproduce an error in some minimum compilable example, so I had to provide you a bigger part of the code.

I'm using these 2 datasets:
[ 1 ] https://www.unsw.adfa.edu.au/unsw-canberra-cyber/cybersecurity/ADFA-NB15-Datasets/a%20part%20of%20training%20and%20testing%20set/UNSW_NB15_training-set.csv
[ 2 ] https://www.unsw.adfa.edu.au/unsw-canberra-cyber/cybersecurity/ADFA-NB15-Datasets/a%20part%20of%20training%20and%20testing%20set/UNSW_NB15_testing-set.csv

and trying to read and decode it...
[reader.zip](https://github.com/ben-strasser/fast-cpp-csv-parser/files/5504783/reader.zip)

**Comment by ben-strasser** [comment]
Hi,

compile your program with -fsanitize=address. It will crash with an 
error message and stacktrace. There is a problem with encoder[ i ].name 
in encodeValue. Are you setting your null terminators for 
encoder[i].name? I do not see where. If not, that is your bug. Anyway, I 
a fairly certain that this is not a bug in the CSV library.

Best Regards
Dr. Ben Strasser

**Comment by lk-dll** [comment]
Hi Ben,

thank you for your help, **-fsanitize=address** helped me, the problem wasn't null terminators, but I made a mistake and declared the number of lines for test_dataset( God is witness that I checked it thousand times ) and Call Stack pointed to CSVReader and LineReader, so sorry for that, but thank you anyway.

Best Regards
