### ISSUE TITLE
forwarding to LineReader issue

### ISSUE THREAD

**Issue by jkhoogland** [ben-strasser/fast-cpp-csv-parser#13]
Hi,

when trying to pass in a istream& in [here](https://github.com/ben-strasser/fast-cpp-csv-parser/blob/master/csv.h#L1125), clang barfs because it tries to call a copy ctor.

The proper fix is to make the argument take a universal ref...

```
explicit CSVReader(Args&&...args):in(std::forward<Args>(args)...){
```

Cheers
Jiri

**Comment by ben-strasser** [comment]
Fix pushed
