### ISSUE TITLE
How to read a cell that have many line?

### ISSUE THREAD

**Issue by ancuop** [ben-strasser/fast-cpp-csv-parser#29]
When a cell in .csv file that has many lines, It throws exception "Too few columns in line ... ".
I can not read it as char *, please teach me how to solve it.
Thanks

**Comment by ben-strasser** [comment]
I do not fully understand the questions, but if you are referring to string with newlines in them:  Not supported. The rational for this decision is here: https://github.com/ben-strasser/fast-cpp-csv-parser/issues/2#issuecomment-109916664
