### ISSUE TITLE
Fails to parse string with four consecutive quotes! 

### ISSUE THREAD

**Issue by niranjan92** [ben-strasser/fast-cpp-csv-parser#3]
Fails to parse following input: 
```
"Id","Title","Body","Tags"^M 
"1","How to check if an uploaded file is an image without mime type?","<p><img src="http://i.stack.imgur.com/bA7Tz.jpg" alt=""""></p>
","php image-processing file-upload upload mime-types"^M 
```

The output for Body column should be
 ```
<p><img src="http://i.stack.imgur.com/bA7Tz.jpg" alt=""></p>
```
But the ouput is: 
```
<p><img src="http://i.stack.imgur.com/bA7Tz.jpg" alt="></p>
```

**Comment by gcflymoto** [comment]
how do you expect that to be legal? shouldn't quotes be escaped?

**Comment by niranjan92** [comment]
Its not an outright error. 

But the library doesn't support that functionality. I think Excel to csv conversion results in such data. http://stackoverflow.com/questions/25064422/excel-to-csv-to-txt-cells-with-double-quotes

As per wiki: http://en.wikipedia.org/wiki/Comma-separated_values
```
Embedded double quote characters may then be represented by a pair of consecutive double quotes,[9] or by prefixing an escape character such as a backslash (for example in Sybase Central).
```

**Comment by ben-strasser** [comment]
Hi,

thanks for the bug report. I can confirm the problem. The erroneous code 
is in line 601.

char*out = col_begin;
for(char*in = col_begin; in!=col_end; ++in){
   if(*in == quote && *(in+1) == quote){
     continue;
   }
   *out = *in;
   ++out;
}

When unescaping the string the code drops every " that is followed by 
another ". This is correct in the case of "bla""foo""bar" but fails in 
the case of "foo""""bar".

Does the following code work for you? (I currently do not have the time 
to test.)

char*out = col_begin;
for(char*in = col_begin; in!=col_end; ++in){
   if(*in == quote && *(in+1) == quote){
     ++in;
   }
   *out = *in;
   ++out;
}

Best Regards,
Ben Strasser

**Comment by niranjan92** [comment]
yes, the given fix works! Thanks. :)
