### ISSUE TITLE
fatal error C1083: Cannot open include file: 'cerrno': No such file or directory

### ISSUE THREAD

**Issue by jaimestuardo** [ben-strasser/fast-cpp-csv-parser#35]
How can i compíle? I am using VC++ 2008

**Comment by ben-strasser** [comment]
Hi,

Option 1 (strongly recommended): Upgrade your compiler. Your compiler is 9 years old. You will run into heaps of further problems with that compiler down the road.
Option 2: Replace <cerrno> with <errno.h>

Best Regards
Ben Strasser
