### ISSUE TITLE
Can this read a CSV file that only has numbers, in one go? 

### ISSUE THREAD

**Issue by anshulvj** [ben-strasser/fast-cpp-csv-parser#39]
So I have a csv file which contains 480 rows of 640 comma-separated numbers (so 640 columns of 480 values each) - representing a 480x640 matrix that was stored in the csv file. Is it possible to read this file into a cv::Mat or a standard float[][] matrix in C++ in one go? i.e. instead of copying 640 columns and figuring out the mapping to a Mat, can this copy all this data into a matrix? I don't have any headers.

**Comment by ben-strasser** [comment]
You can use the LineReader to read a file line by line but you will have to split the line by hand.
