### ISSUE TITLE
Work with stream

### ISSUE THREAD

**Issue by pendenaor** [ben-strasser/fast-cpp-csv-parser#4]
Hello,

My current application need to parse a CSV stream produced by a WebService.
Presently, i have to write it down to disk to use your parser, maybe it would be useful to create an interface for (string)stream ?

**Comment by ben-strasser** [comment]
The newest version has support for arbitrary istreams. You can added other data sources (such as a socket) by deriving a class from ByteSourceBase and implementing that functionality.
