### ISSUE TITLE
Separate csv.h into several header files

### ISSUE THREAD

**Issue by eyalroz** [ben-strasser/fast-cpp-csv-parser#44]
This is a nice little library, but "header-only" should not mean "one header only", and 1200 lines, while not terrible, is still a lot for just a CSV parser. There are clear cutoff points for separating out several header files; certainly `LineReader` and `CSVReader` can have files of their own.

... and then you tie it all together with a `csv.h` that includes the different header files.

**Comment by ben-strasser** [comment]
Hi, 

thanks for the feedback. However, dropping the library into a project is vastly easier if it is composed of a single header. I see no major benefit in breaking the header into multiple files.

Best Regards
Ben Strasser

**Comment by eyalroz** [comment]
Well, I personally don't think dropping 3 files is that much different than dropping 1 file, but it's your call :-)
