### ISSUE TITLE
Doesn't work if a cell contains comma

### ISSUE THREAD

**Issue by trehman65** [ben-strasser/fast-cpp-csv-parser#46]
a,b,c
1,"23,3",44
23,545,56

I get libc++abi.dylib: terminating with uncaught exception of type io::error::too_many_columns: Too many columns in line 2 in file "/Users/talha/Coding/ClionProjects/pricerightnlp/test.csv".

**Comment by ben-strasser** [comment]
Hi,

thanks, for your feedback. Why does the example from the documentation not work for you?

> Examples:
> CSVReader<4, trim_chars<' '>, double_quote_escape<',','\"'> > reads 4 columns from a normal CSV file with string escaping enabled.

Best Regards
Ben Strasser

**Comment by tuanhtrng** [comment]
Hi @ben-strasser,

I tested your example and it worked as intended.

**Comment by Ninja-007** [comment]
Thanks @trehman65  and @ben-strasser 
I am interested in knowing import of CSV cells which have commas inside and enclosed by "". 
Did you above mentioned example work? 
a,b,c
1,"23,3",44
23,545,56

**Comment by ben-strasser** [comment]
You asked with "Did that work?" after someone wrote in the exact post before yours "That works". What answer do you expect?
