### ISSUE TITLE
Optional Values

### ISSUE THREAD

**Issue by benjamin0** [ben-strasser/fast-cpp-csv-parser#47]
I have a `.csv` file with data that looks like the following:
```
a,b,c
1,2,3
1,,3
1,2,3
```
I'd like to know that there's no `b` value for the second line (rather than interpreting it as `0`). Is it possible to do this?

**Comment by ben-strasser** [comment]
Hi,

does the following code work for you?

int a, b, c;
char*b_str;
while(in.read_row(a,b_str,c)){
	if(*b_str == '\0'){
		// No b
	} else {
		b = atoi(b_str);
		// there is a b
	}
}

Best Regards
Ben Strasser

**Comment by Ninja-007** [comment]
I would like to know what will happen in case of 'b' value is not present. 
1. Will the library throw error or issue just warning?
2. Is there any option to enable or disable these behaviours?

**Comment by ben-strasser** [comment]
As stated in the top comment: The default is interpret an empty field as zero value. If you want something else you must read a char* and do the parsing yourself.
