### ISSUE TITLE
CSV Parser memory footprint for large file

### ISSUE THREAD

**Issue by Ninja-007** [ben-strasser/fast-cpp-csv-parser#50]
I want to use this library on embedded device which has limited processing power and memory.
The size of CSV file to be imported is around 200KB - 500KB.

1. How does the library handles reading of this file? Does it read everything in one shot? Or does it read single row at a time? 
2.  Is it possible to specify number of row which should be read at a time? For example 20 rows at time, after processing them ask for another 50.
3. Do you have any memory benchmarks? If no, how much memory will the library allocate? 

Regards

**Comment by ben-strasser** [comment]
You might want to play with block_len in line 316.
