### ISSUE TITLE
Feature Request: Load gzipped csv files

### ISSUE THREAD

**Issue by xgdgsc** [ben-strasser/fast-cpp-csv-parser#53]
Is there any plan on supporting loading some format of compressed csv files. It is very common people compress csv files to save space on disk and reduce I/O.

**Comment by ben-strasser** [comment]
Hi,

You can do so by deriving a class from ByteSourceBase.

Best Regards
Ben Strasser

**Comment by xgdgsc** [comment]
Thanks I plan to try.

**Comment by xgdgsc** [comment]
You may not want to add dependencies like boost. I posted my simple compressed csv reader [here](https://gist.github.com/xgdgsc/22227ac7992226920a5bee3ef409bd65) in case someone needs.
