### ISSUE TITLE
3 buffers vs double buffer 

### ISSUE THREAD

**Issue by romange** [ben-strasser/fast-cpp-csv-parser#56]
Hi Ben,

This is not really an issue, just a question. I've read your code (async part) and I noticed that you used 3 buffers: every time you complete the first buffer you copy the second to the beginning, wait for the last third to complete and then you copy it as well . What's the reason for this design? 
Why not using just double-buffer technique: parse from the first part while asynchronously read into the second half, wait for it to complete and then to parse the second part, asynchronously reading from the first part. It seems simpler so I am guessing there is a catch.

**Comment by ben-strasser** [comment]
Hi,

lines can span two blocks. The consumer can therefore not fully cosume 
his block until the producer is finished with the next one. However, the 
producer cannot finish if he has no new block to move to. We therefore 
have three blocks.

Best Regards
Ben Strasser

**Comment by romange** [comment]
Thanks! That explains it  :+1:
