### ISSUE TITLE
CSV files with LF as part of data

### ISSUE THREAD

**Issue by wolframbeta** [ben-strasser/fast-cpp-csv-parser#57]
So I'm trying to parse a .CSV file that has a data member that is distinguished by quotes, but contains line feed in it.
Example line with 3 elements:
Colors,3,"Red
Blue
Green"
Is there a way to parse this with your tool? It seems to read: Colors,3,"Red, and then throw an escaped string not closed error, or a not enough columns error if i dont use escape strings. Any solutions?

**Comment by ben-strasser** [comment]
Hi,

Thanks for the feedback. Unfortunately, newlines in quotes are not supported. There are technical reasons for this but I also consider CSV files where a row spans multiple lines broken. There are older issues on github that contain a more detailed rational as to why.

Best Regards
Ben Strasser

**Comment by paulharris** [comment]
You could try my library,
https://github.com/paulharris/cppcsv

It supports all that kind of thing.
Not sure if its faster than fast-cpp-csv-parser, but its pretty quick.
