### ISSUE TITLE
error: ‘in’ does not name a type

### ISSUE THREAD

**Issue by chengjiehuang** [ben-strasser/fast-cpp-csv-parser#61]
Hi Ben Strasser,

I really love your code, but when I try to complie the sample code in the section: 
[https://github.com/ben-strasser/fast-cpp-csv-parser#getting-started](url)
I got an error: 'in' does not name a type.

`# include "csv.h"`
`int main()`
`{`
`  io::CSVReader<3> in("ram.csv");   // no error here.`
`  in.read_header(io::ignore_extra_column, "vendor", "size", "speed"); // error: 'in' does not name a type.`
`  std::string vendor; int size; double speed;`
`  while(in.read_row(vendor, size, speed))`
`  {`
`    // do stuff with the data`
`  }`
`}`

It's weird... Could you give me some hint where there is a problem.

Thanks,
Chengjie

**Comment by benslaney** [comment]
Can you say what the solution was? I'm having the same problem when using the example from the front page

```
tester.cpp:4:3: error: use of undeclared identifier 'io'
  io::CSVReader<3> in("ram.csv");
  ^
tester.cpp:4:20: error: use of undeclared identifier 'in'
  io::CSVReader<3> in("ram.csv");


```

**Comment by chengjiehuang** [comment]
Hi Ben, I found that I wrongly put “#include “csv.h”” in a namespace. So I closed this issue.
