### ISSUE TITLE
does not parse part of a file

### ISSUE THREAD

**Issue by pgallir** [ben-strasser/fast-cpp-csv-parser#7]
very nice. but I needed to read only some lines of a file, and only some parameters from these lines. this is why I decided unwillingly to do something worse myself... (https://github.com/pgallir/easy-cpp-subfile-parser). 
by the way, this could be an useful features for many. as far as I am concerned, you should introduce this feature in your lib.

**Comment by gcflymoto** [comment]
not really. filtering can be done in the app instead of the library.

**Comment by pgallir** [comment]
as in my case, if you know in advance that you need just part of it, why not to avoid reading it all? I mean, are we still talking about how to reduce time in parsing big files?

**Comment by gcflymoto** [comment]
there is already a mechanism to skip the columns you dont need. Are you talking about something different? As far as filtering based on line numbers, that's what git forking is for. If you want your own functionality, which the owner of this repo might not want, you can add it to your own.

**Comment by pgallir** [comment]
I might be wrong, but it seems the mechanism you mean happens to be just a selection of the first some columns, which is a complete different behaviour from specific columns' selection. Hope you'll understand. Same story for the rows. 
In any case, as you should have noticed from my first post, I already successfully coded and shared it. In other words, mine was not a request but a sharing. Hence, please read before posting next time. g-night.

**Comment by gcflymoto** [comment]
The capability is already there for picking specific columns if you read the documentation
"""
ignore_extra_column: If a column with a name is in the file but not in the argument list, then it is silently ignored.
"""

There is no capability for row selection
