### ISSUE TITLE
Support for escaped separators and newlines

### ISSUE THREAD

**Issue by eyalroz** [ben-strasser/fast-cpp-csv-parser#71]
I'f I'm not mistaken, the library doesn't currently support CSV files in which quoted strings contain column separators or newlines. Such support should be added; and while it is missing, the README should indicate that only a subset of the CSV specification is supported.

**Comment by ben-strasser** [comment]
Newlines are not allowed in quoted strings. Column separators are 
allowed, if you use the right policies.

**Comment by eyalroz** [comment]
Newlines are most certainly allowed in quoted fields. The CSV spec ([RFC 4180](https://tools.ietf.org/html/rfc4180#)) specifically mentions this in [Section 2.6](https://tools.ietf.org/html/rfc4180#page-2): 

>  2.  Definition of the CSV Format
>  
>  ...
> 
>      6.  Fields containing line breaks (CRLF), double quotes, and commas
>          should be enclosed in double-quotes.  For example:
>
>             "aaa","b CRLF
>             bb","ccc" CRLF
>             zzz,yyy,xxx
