### ISSUE TITLE
How can get rows number of CSV file

### ISSUE THREAD

**Issue by K-JW** [ben-strasser/fast-cpp-csv-parser#78]
Hello Ben Strasser,

Thanks for you give ours this good project. Now, I have a question, I want to create an array and save all data, which is from the CSV file. 
In other words, I want to get rows size of CSV file. But I don't find any useful methods(or function) to get this information. Yes, we can use some method as follow get this number, 

```c++
int num=0;
while(inFile.read_row(a, b)) {
     num++;
 }
```
but I think it isn't an elegant manner, so how can I do? Thanks!

**Comment by ben-strasser** [comment]
You can get the current line number using get_file_line. It is technically infeasible to get the number of lines without looking at every byte of the CSV file. Your pattern is therefore not far from being the best there is.

If you want to read the file in one scan, use std::vector and push_back. Reading a file in one scan is probably faster, than scanning the file twice.
