### ISSUE TITLE
reuse variable

### ISSUE THREAD

**Issue by raulvc** [ben-strasser/fast-cpp-csv-parser#8]
I know it's probably a bad design but I'm trying to find a way to reuse an existing CSVReader instance for reading another file so that I can treat a lot of csv files as a single merged file, any ideas? (I can't iterate on a list of files either as there's no offset setting on the library to return to last read row when I have to stop the iteration midway)

**Comment by ben-strasser** [comment]
Do you have lines that span across multiple files?

If not, then why not doing sometime along:

string file_list[] = {...};
for(const auto& x:file_list){
     CSVReader<3>in(x);
     in.read_header(...);
     while(in.read_row(...)){

     }
}
