### ISSUE TITLE
Declare headers

### ISSUE THREAD

**Issue by viettahg** [ben-strasser/fast-cpp-csv-parser#86]
I don't want to insert these columns `"turn_angle_x", "turn_angle_y",` "turn_angle_z" in read_header.
Because lib knows all header columns
`in.read_header(io::ignore_extra_column, "turn_angle_x", "turn_angle_y", "turn_angle_z");`
→`in.read_header()
I just get which columns I want. Like that.
`in.read_row(turn_angle_x, turn_angle_y, turn_angle_z)`

How can I do that?

**Comment by ben-strasser** [comment]
I do not understand your question. Maybe `set_header` is what you are looking for.
