### ISSUE TITLE
A new policy delimiter would be helpful

### ISSUE THREAD

**Issue by gisfromscratch** [ben-strasser/fast-cpp-csv-parser#95]
Usually a bunch of text delimited files are using a tab or semicolon as the delimiter. It is possible to define another delimiter for the `CsvReader<delim_chars<'\t'>>`?

**Comment by eivan** [comment]
Hi, what about `no_quote_escape`?
```cpp
io::CSVReader<7, io::trim_chars<' ', '\t'>, io::no_quote_escape<';'>> asd;
```

**Comment by ben-strasser** [comment]
I close this, as I assume that @eivan answered the question. If his answer does not help, then please reopen. :)

@evian Thanks for answering the question!
