### ISSUE TITLE
question

### ISSUE THREAD

**Issue by jiapengwen** [ben-strasser/fast-cpp-csv-parser#96]
i find doc suggesst With GCC it is important to add -lpthread as the last item when linking  ，
but why？ please help me

**Comment by vanNul** [comment]
for better performance, if pthread is available, then asynchronous reading will work

**Comment by ben-strasser** [comment]
The library supports asynchronous file reading. This is done with multiple threads. To make this work, you need pthread. There is a preprocessor define that deactivates this feature. By using this, you can avoid the need for pthread.
