### ISSUE TITLE
can this parser support json string?

### ISSUE THREAD

**Issue by waterfronter** [ben-strasser/fast-cpp-csv-parser#98]
hi, in my application, I want to parse json string in csv file, like this:
![json_string_in_csv](https://user-images.githubusercontent.com/50987245/76138888-23c1a980-6086-11ea-84b0-6adc3e07671d.png)
can this parser parse row NO.2 values as a line and assign values in columns to key "Module", "Function", "Param", "Expect", "Result", "Info" respectively？
looking forward your response, thank you!

**Comment by ben-strasser** [comment]
Quoted strings without non-escaped newlines work. The library does not care whether this is JSON or not.
